# Generated by Django 5.2.7 on 2025-10-25 21:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SheetMusic', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Measure',
            new_name='SheetMusic',
        ),
    ]
