# Generated by Django 5.2.7 on 2025-10-26 06:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SheetMusic', '0002_rename_measure_sheetmusic'),
    ]

    operations = [
        migrations.CreateModel(
            name='Measure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(db_index=True, editable=False, verbose_name='order')),
                ('duration', models.PositiveIntegerField()),
                ('pitch', models.CharField()),
                ('initialized', models.BooleanField()),
                ('measure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='SheetMusic.measure')),
            ],
            options={
                'ordering': ('order',),
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='SheetMusic',
        ),
    ]
